# Generated by Django 3.1.4 on 2020-12-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='sqft',
            field=models.IntegerField(),
        ),
    ]
